-- ============================================================================
-- Trend Break Reports Schema
-- ============================================================================
-- Stores automated trend break report entries generated by Airflow DAGs.
-- Each row = one flagged security (>=80% probability) in one report run.
-- Denormalized for fast reads: no joins required at query time.
-- ============================================================================

CREATE TABLE IF NOT EXISTS trend_break_reports (
    id SERIAL,
    report_id UUID NOT NULL,
    report_frequency VARCHAR(15) NOT NULL,        -- 'daily', 'hourly', '10min'
    report_generated_at TIMESTAMPTZ NOT NULL,

    -- Security identification
    ticker VARCHAR(10) NOT NULL,
    sector VARCHAR(50),
    sector_etf VARCHAR(10),

    -- Trend break prediction
    break_probability DECIMAL(6, 4) NOT NULL,     -- >= 0.80 threshold
    break_direction VARCHAR(10),                  -- 'bullish' or 'bearish'
    confidence DECIMAL(6, 4),

    -- Recency alert
    is_recent_alert BOOLEAN DEFAULT FALSE,
    first_crossed_at TIMESTAMPTZ,
    consecutive_reports INTEGER DEFAULT 1,

    -- Price data
    current_price DECIMAL(12, 4),
    price_change_pct DECIMAL(10, 4),

    -- Indicator values (denormalized)
    cci_value DECIMAL(10, 2),
    stochastic_k DECIMAL(10, 2),
    stochastic_d DECIMAL(10, 2),
    rsi_value DECIMAL(10, 2),
    adx_value DECIMAL(10, 2),
    tlev_value DECIMAL(10, 4),
    sma_20 DECIMAL(12, 4),
    sma_50 DECIMAL(12, 4),

    -- Sector sentiment context
    sector_sentiment VARCHAR(10),
    sector_confidence DECIMAL(6, 4),

    -- Options summary (denormalized)
    options_available BOOLEAN DEFAULT FALSE,
    nearest_call_strike DECIMAL(12, 4),
    nearest_call_fair_value DECIMAL(12, 4),
    nearest_put_strike DECIMAL(12, 4),
    nearest_put_fair_value DECIMAL(12, 4),
    implied_volatility DECIMAL(10, 4),

    -- Metadata
    model_version VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT NOW(),

    PRIMARY KEY (report_id, ticker)
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_tbr_frequency_time
    ON trend_break_reports (report_frequency, report_generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_tbr_ticker_time
    ON trend_break_reports (ticker, report_generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_tbr_recent_alerts
    ON trend_break_reports (report_frequency, report_generated_at DESC)
    WHERE is_recent_alert = TRUE;

CREATE INDEX IF NOT EXISTS idx_tbr_report_id
    ON trend_break_reports (report_id);

-- Optional: TimescaleDB hypertable (only if extension is available)
-- SELECT create_hypertable('trend_break_reports', 'report_generated_at',
--     chunk_time_interval => INTERVAL '1 week',
--     if_not_exists => TRUE
-- );

-- Grants
GRANT ALL PRIVILEGES ON trend_break_reports TO trading;
